version: 0.2
phases:
  install:
    commands:
      - sam package --template-file HW2/samTemplate.yaml --s3-bucket photoalbum-asset-bucket --output-template-file outputsamtemplate.yml
artifacts:
  type: zip
  files:
    - HW2/samTemplate.yaml
    - outputsamtemplate.yml
