version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file HW2/samTemplate.yaml --s3-bucket photoalbumcoms2 --output-template-file outputsamtemplate.yml
artifacts:
  type: zip
  files:
    - HW2/samTemplate.yaml
    - outputsamtemplate.yml
