version: 0.1
phases:
  install:
    commands:
      - aws cloudformation create-stack --stack-name photoAlbumStack --template-body HW2/CloudFormation.yaml --capabilities CAPABILITY_AUTO_EXPAND
      - aws cloudformation package --template-file HW2/samTemplate.yaml --s3-bucket photoalbum-asset-bucket --output-template-file outputsamtemplate.yml
artifacts:
  type: zip
  files:
    - HW2/samTemplate.yaml
    - outputsamtemplate.yml
