version: 0.1
phases:
  install:
    commands:
      - sam build —-template-file HW2/samTemplate.yaml
      - sam deploy —-template-file .aws-sam/build/template.yaml -—stack-name stack-photoAlbum
artifacts:
  type: zip
  files:
    - HW2/samTemplate.yaml
